### ISSUE TITLE
LPC176x CanBoot and Klipper flashing

### ISSUE THREAD

**Issue by idontknowtom** [Arksine/CanBoot#29]
I was looking to use this for my SKR 1.4 with LPC1768 but noticed the instructions are heavily based around the STM32 devices. I have flashed a BTT EBB36 using CanBoot and want to add CanBoot to the SKR 1.4

Any tips on flashing CanBoot, setting up Klipper (smoothieware bootloader, so no bootloader options available), and flashing Klipper?

**Comment by githubcura35** [comment]
Please see https://klipper.discourse.group/t/canboot-flash-btt-skr-1-3-1-4-1-4-turbo/3238
