### ISSUE TITLE
CanBoot for RP2040

### ISSUE THREAD

**Issue by JonathanHeinz** [Arksine/CanBoot#42]
Possibility to install CanBoot on a RP2040 Chip

Example code:
https://github.com/rhulme/pico-flashloader

Blog entry for building a custom RP2040 bootloader:
https://blog.usedbytes.com/2021/12/pico-serial-bootloader/

**Comment by bwshockley** [comment]
I will second this request, with the understanding this is a big request.  I'm specifically using the Mellow Fly-SB2040 board and suspect other CANBUS boards will be moving to the RP2040.

**Comment by tillin9** [comment]
I'll also +1 this request as I have an SB2040. Thanks all.

**Comment by sh83** [comment]
This is my attempt on this: 
https://github.com/Arksine/CanBoot/pull/45

**Comment by akhamar** [comment]
Would be nice indeed !

**Comment by JonathanHeinz** [comment]
> This is my attempt: #45

Can i close the ticket now?

**Comment by sh83** [comment]
> Can i close the ticket now?
I think it should be closed when klipper pr ( https://github.com/Klipper3d/klipper/pull/5874 ) will be merged.

**Comment by jtrmal** [comment]
been merged just a while ago.
y.
