### ISSUE TITLE
Entry bootloader with external pin. 

### ISSUE THREAD

**Issue by xsnoopy** [Arksine/CanBoot#48]
Hi, I have the creality Ender 6 with the V4.3.1 board. I compiled the bootloader with the attached .config file. 

I flashed the bootloader with STM32 Cube Programmer, and see that it's flashed.

However, I can not get into bootloader mode and flash with stm32flash on Linux using this command for flashing the klipper firmware. I connected PB 11 to high and plugged the board in USB. 

 stm32flash -w out/klipper.bin -v -b 230400 -g 0x08002000 /dev/ttyUSB1

[config.txt](https://github.com/Arksine/CanBoot/files/9941221/config.txt)

**Comment by Arksine** [comment]
The `stm32flash` tool is used with ST's system bootloader, it can't be used with CanBoot.  You must use [flash_can.py](https://github.com/Arksine/CanBoot#uploading-klipper).

**Comment by xsnoopy** [comment]
Ok, if I use the flash_can.py, how does it know where to write the klipper.bin to? EG I need it to be starting at adsress 0x08002000.

**Comment by Arksine** [comment]
The bootloader itself knows (it was presumably configured with an 8KiB offset).  It will tell `flash_can.py` where the application address should start.

**Comment by xsnoopy** [comment]
Appreciate your fast response.
For the bootloader that's c;ear, depending if I use 4 or 8 kbit offset it will jump to that address. 

But how doesflash_can.py know on which page to start with the klipper.bin file.

**Comment by Arksine** [comment]
CanBoot is configured with an `application start offset`.  This is where the application must always begin, CanBoot cannnot be used to arbitrarily write to areas of flash like DFU or the `stm32flash` utility.  The application (in this case Klipper) must be configured with a matching bootloader offset.

After `flash_can.py` connects to the bootloader it queries information about it.  The application start address is one of the items returned.

**Comment by xsnoopy** [comment]
Ah, understood. I tried to connect with flash_can.py I tried starting with connecting PB 11high and then plug in the board as well as plug in the board and then connect PB 11 high. flash_can.py exits with this error. 

```
ERROR:root:Can Read Error
Traceback (most recent call last):
  File "flash_can.py", line 137, in send_command
    ret = await self.node.readuntil()
  File "flash_can.py", line 287, in readuntil
    return await asyncio.wait_for(self._reader.readuntil(sep), timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutErro
```r

**Comment by Arksine** [comment]
That suggests that the bootloader isn't running.  Make sure the baud rates match and make sure that the application is flashed starting at 0x0800000.

**Comment by xsnoopy** [comment]
I can confirm that the baud rate (230400) is correct and the bootloader is compiled as it and written to 0x0800000.  I made a full chip erase before I flashed the bootloader. I can upload some pictures from cube programmer which shows that it's correct flashed.

**Comment by xsnoopy** [comment]
![image](https://user-images.githubusercontent.com/63822202/200116963-ec1a3576-768a-4b32-b49d-7a564d4cc003.png)

**Comment by Arksine** [comment]
The Creality boards are notoriously difficult to get working with 3rd party software as no schematic is provided, seems like CanBoot is no exception.  The only remaining recommendation I can make is to doublecheck that the CanBoot build configuration is correct.

- Verify the Clock Reference
- Verify that the ttl chip is connected to the pins on USART1
- Try to build with 250000 baud

Another think you could try is to wire up an led and enable the LED option in the build.  That way you can visually verify that CanBoot is running, as the led will blink slowly.

**Comment by xsnoopy** [comment]
I agree the fact that they neither have reset or Boot0 connected, is enough pain... I would never use one of those boards if it wouldn't come with the printers I have. 

I will try what you said, but it might take some time. 

The LED is that Enable Status LED? Or GPIO pins to set on bootloader entry?

Would it be possible to add just a few seconds delay timer in the bootloader? That way I could save a GPIO Pin.

**Comment by Arksine** [comment]
> The LED is that Enable Status LED? Or GPIO pins to set on bootloader entry?

It is `Enable Status LED`.  When you select it an input for the LED pin will show up in the menuconfig.

> Would it be possible to add just a few seconds delay timer in the bootloader? That way I could save a GPIO Pin.

Unfortunately not.  A delay can negatively affect Klipper after issuing a FIRMWARE_RESTART.  One of the motivations behind CanBoot was to create a bootloader that we could tailor to work well with Klipper.

FWIW, you really only need the LED for testing.  Once you have determined that the bootloader is running you can go back and disable it to free up that pin.  That said, the led pin can be dual use as long as whatever is connected to it during normal use can tolerate being toggled on/off.

**Comment by xsnoopy** [comment]
Got it working. Baud 250000 worked, 230400 did not.
