### ISSUE TITLE
[Feature Request] - Option to only trigger DFU mode over canbus without trying to flash the device

### ISSUE THREAD

**Issue by Norbs12** [Arksine/CanBoot#62]
When running octopus pro in can bridge mode.
I found that I can use canboot flash over canbus to trigger DFU mode on the octopus but not flash it over canbus. This however makes the octopus show up as a serial stm device in DFU mode, at which point I can just flash over serial. Once flashed it shows up as a can device again.

Is there a command or would it be possible to add a command to simply trigger DFU without attempting to flash?

This would be useful for scripting and avoiding all the errors that get generated by intentionally doing a failed flash over canbus, just to trigger the stm serial dfu mode.

**Comment by Norbs12** [comment]
Thanks for this!

`-r, --request-bootloader
                        Requests the bootloader and exits (CAN only)`

**Comment by Arksine** [comment]
YW.  This makes sense, it didn't occur to me that Klipper could jump to the Bootloader when the USB-CAN bridge is enabled.  This should work with any bootloader, including CanBoot-USB.

If I can figure out how to determine the correct USB device path from the socketcan interface I may be able to implement this in Klipper's `flash_usb.py`, which would automate the entire process of flashing a USB-CAN bridge via `make flash`.

**Comment by Norbs12** [comment]
After triggering DFU, the serial device appears immediately, so maybe you can monitor for new devices that contain "stm32" in it? There might be something more you can do to check if it's ready for flashing because I found if I don't want 22 seconds or more, it ends up failing and I have to start over (reboot board, trigger DFU over canbus, wait 22 sec, flash over serial).

To get around it I just run this but unfortunately there is no error handling, and I'm not sure why the board needs that large of a sleep before it will flash successfully. Using "sleep" feels so hokey, but it works pretty reliably...

`
## after triggering DFU over canbus
sleep 22
python3 ~/CanBoot/scripts/flash_can.py -f ~/klipper/out/klipper.bin -d $(ls /dev/serial/by-id/* | grep stm32f446 )

`

I believe there might be a similar stm32 name for
